#!/bin/bash

main() {
    # Allow workers to execute direct commands in the container (php artisan queue:work, etc.)
    if [ "$IS_WORKER" = "true" ]; then
        # su-exec drops root privileges and runs the command as www-data
        exec su-exec www-data "$@"
    else
        prepare_storage
        run_migrations
        optimize_app
        run_server "$@"
    fi
}

prepare_storage() {
    echo "Preparing storage permissions..."
    chown -R www-data:www-data /usr/share/caddy/html/storage
    chown -R www-data:www-data /usr/share/caddy/html/bootstrap/cache
    chmod -R 775 /usr/share/caddy/html/storage
    chmod -R 775 /usr/share/caddy/html/bootstrap/cache
    php artisan storage:link
}


run_migrations() {
    echo "Running database migrations..."
    attempt=1

    until ./artisan migrate --force; do
        if [ "$attempt" -ge 30 ]; then
            echo "Migration failed after ${attempt} attempts."
            exit 1
        fi

        attempt=$((attempt + 1))
        sleep 2
        echo "."
    done
}

optimize_app() {
    ./artisan optimize:clear
    ./artisan optimize
}

run_server() {
    exec /usr/local/bin/docker-php-entrypoint "$@"
}

main "$@"
